name: Pipeline
on:
  create
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - name: Print branch currently name
      if: steps.branch-name.outputs.is_default == 'true'
      run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
    - name: Run bash script to custom app name
      run : |
          chmod +x "${GITHUB_WORKSPACE}/.github/nameCheck.sh"
          "${GITHUB_WORKSPACE}/.github/nameCheck.sh" ${{ steps.branch-name.outputs.current_branch }}
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{env.CUSTOM_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}