name: Destroy heroku App
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - name: Print branch name
      if: steps.branch-name.outputs.is_default == 'true'
      run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
    - name: Use action heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        justlogin: true
    - run: |
          heroku apps:destroy ${{secrets.HEROKU_APP}}-${{ steps.branch-name.outputs.current_branch }}