name: Destroy heroku App
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - name: Parse branch name
      run : |
          branch_original_name=${{ steps.branch-name.outputs.current_branch }}
          branch_prefix=$(echo $branch_original_name | cut -d '/' -f 1)
          branch_name=$(echo $branch_original_name | cut -d '/' -f 2)
          branchNameUntil30Chars=${branch_name:0:30}
          heroku_name=$branch_prefix"/bt-events-"$branchNameUntil30Chars
          echo "CUSTOM_NAME=$heroku_name" >> $GITHUB_ENV
    - name: Required pattern name
      if: $branch_prefix == "feature" || $branch_prefix == "bugfix" || $branch_prefix == "hotfix"  
    - name: Use action heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        justlogin: true
    - run: |
          heroku apps:destroy ${{env.CUSTOM_NAME}} --confirm ${{env.CUSTOM_NAME}}