name: Destroy heroku App
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - name: Run bash script to custom app name
      run : |
          chmod +x "${GITHUB_WORKSPACE}/.github/nameCheck.sh"
          "${GITHUB_WORKSPACE}/.github/nameCheck.sh" ${{ steps.branch-name.outputs.current_branch }}
    - name: Use action heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        justlogin: true
    - run: |
          heroku apps:destroy ${{env.CUSTOM_NAME}} --confirm ${{env.CUSTOM_NAME}}